[package]
name = "rust_ti"
version = "0.0.1"
edition = "2021"
authors = ["0100101001010000"]
description = "Rust TI, the most configurable Technical Indicators package available"
repository = "https://github.com/0100101001010000/rustTI"
license = "MIT"
keywords  = ["trading", "technical-analysis", "finance", "indicators"]
categories = ["finance", "mathematics"]
exclude = ["/assets", "/.git", "/.github"]

[[example]]
name = "sp500"
path = "examples/main.rs"

[dependencies]
